# Hermes/dockerfile
#어떤 환경에서 작업할 건지 설정
FROM ubuntu:18.04

#'HERMES_SERVER' 하위 디렉토리에 폴더 생성
RUN mkdir -p /HERMES_SERVER

# /app 으로 이동
WORKDIR /app

# 우분투리눅스 upgrade AND update
# ADD -> local에서 파일 가져오기
RUN ADD . /app/

#  Asia/Seoul 로 환경설정 / UTF-8 로 encode 설정
ENV TZ=Asia/Seoul\
    LANG="C.UTF-8" \
    LC_ALL="C.UTF-8" 

#zoneinfo에 Asia/Seoul로 Timezone 설정
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone


RUN apt-get -y upgrade \
    && apt-get -y update \
		#파이썬 Download에 필요한 라이브러리들
    && apt-get -y install build-essential checkinstall \
    && apt-get -y install libreadline-gplv2-dev libncursesw5-dev libssl-dev libsqlite3-dev tk-dev libgdbm-dev libc6-dev libbz2-dev libffi-dev zlib1g-dev \
    && apt-get -y install wget \
    && wget https://www.python.org/ftp/python/3.9.9/Python-3.9.9.tgz \
    && tar xzf Python-3.9.9.tgz \
    && cd Python-3.9.9 \
    && ./configure --enable-optimizations \
    && make altinstall \
    && update-alternatives --install /usr/bin/python python /usr/local/bin/python3.9 1 \ 
    && apt-get -y install python-pip\